### ISSUE TITLE
Register rsa public key fails in thales

### ISSUE THREAD

**Issue by pkumarex** [ThalesGroup/kmip-go#10]
Hi,
    
     I am trying to register a public key using thales kmip-go. From the base64 public key values, hex string is derived..
     For key material, ByteString is needed. So, used golang package to decode the hex string and pass it as input.
     
     This code works with pykmip but not with thales server.
      If I directly provide the hex string as keymaterial, keymaterial type is text string and i am getting keyformat not supported.
      If I provide it as decoded bytes, it shows there is not enough key material.

      This is the working xml payload for thales ,

     <RequestPayload>
      <ObjectType type="Enumeration" value="PublicKey"/>
      <TemplateAttribute>
        <Attribute>
          <AttributeName type="TextString" value="Cryptographic Usage Mask"/>
          <AttributeValue type="Integer" value="UnwrapKey WrapKey"/>
        </Attribute>
      </TemplateAttribute>
        <PublicKey>
          <KeyBlock>
          <KeyFormatType type="Enumeration" value="PKCS_1"/>
          <KeyValue>
            <KeyMaterial type="ByteString" value="30820122300d06092a864886f70d01010105000382010f003082010a0282010100a6aba5b452b2d8f5565862c2a6237609803434be5872808d7c70c8a0ee2c95c1eceac659a2bfeeba53c67b9f423551e1c38a34981981885a0579483a056d932aefaabd796733323e1ca7f3609c215b948d69402c9f03d04f75d22ce83181c20c53eb4fdd512e384bb928a8ef20cfabc58c0267cceb99ddcd8855ba89429821c2e5b83e2d0185dfb0d265bd2fc915fdf9363ffd4e0d65bb4df6ddf214d6f1be45343c8db8702db56f4fe9025e3dd8103d4265570162fc0f62959cd71801d845b189eb3c48c5af0d2d42d0afa5eb2acbd19ab4b83f2337af9eefe3fbe8619fb425b056ce42845b98797af3f5ba53cfaf238f95aee4d529ba040ba5ae1f34f1c6a70203010001"/>
          </KeyValue>
          <CryptographicAlgorithm type="Enumeration" value="RSA"/>
          <CryptographicLength type="Integer" value="2048"/>
          </KeyBlock>
        </PublicKey>
    </RequestPayload>

 Tried the same with kmip-go package. Only difference is 0x prefix gets added in the byteString. 

The request message I tried ,

1) if i decode the hex string to set the key material type as byte string,

key material in request message is 
KeyMaterial (ByteString/322): 0x33303831396533303064303630393261383634383836663730643031303130313035303030333831386330303330383138383032383138303535323565636430343966366663323932656265336438343838663230636333643939343138376635323835653639313738323865636331656462363038306564646231626330326235353234373238643131326234323134633662343534313931333937356163623661353233386137616638343865663936356535626562333333656435643862376439666432316265643462626138633539373236396365323538633935363138623264326136373962646361366465386562346439626166663232366531316535396636353338353933623234336263623731653438666237356466393939383635626139633363376232613464326231646164636630323033303130303031

2) If the keymaterial is directly provide as a string, the correct key material is shown in request message. but type is text string.

  KeyMaterial (TextString/324): 0x30819e300d06092a864886f70d010101050003818c003081880281805525ecd049f6fc292ebe3d8488f20cc3d994187f5285e6917828ecc1edb6080eddb1bc02b5524728d112b4214c6b4541913975acb6a5238a7af848ef965e5beb333ed5d8b7d9fd21bed4bba8c597269ce258c95618b2d2a679bdca6de8eb4d9baff226e11e59f6538593b243bcb71e48fb75df999865ba9c3c7b2a4d2b1dadcf0203010001

0x prefix is added in all the input.
But the working example given in xml format. it shows the correct key material and type.
Can you provide any example on how to provide the request message for this ?

Thank you.

**Comment by ansel1** [comment]
The 0x prefix is just added for display purposes.  It's not actually in the binary payload.  

The value in 1. is definitely wrong, but I'm not sure how/where it was corrupted.  Decoding the hex into a []byte, then setting that in your KeyMaterial TTLV should work.  kmip-go will encode a []byte as a ByteString.

Can you post the code that decodes the hex and then creates and encodes the TTLV value?

There is a utility in kmip-go called ppkmip which can convert TTLV in various forms (json, xml, hex) into other forms.  It's useful for re-formatting or parsing values.  Do a git pull to get the latest fix, and then use `make install` to build and install a copy in $GOBIN.  Use `ppkmip --help` to see the usage. 

I tried it on the XML sample in the ticket, and confirmed that the "0x" prefix is not actually encoded in the binary.  Here's some sample output: 
```
❯ ppkmip -f sample.xml
RequestPayload (Structure/456):
  ObjectType (Enumeration/4): PublicKey
  TemplateAttribute (Structure/56):
    Attribute (Structure/48):
      AttributeName (TextString/24): Cryptographic Usage Mask
      AttributeValue (Integer/4): 48
  PublicKey (Structure/368):
    KeyBlock (Structure/360):
      KeyFormatType (Enumeration/4): PKCS_1
      KeyValue (Structure/304):
        KeyMaterial (ByteString/294): 0x30820122300d06092a864886f70d01010105000382010f003082010a0282010100a6aba5b452b2d8f5565862c2a6237609803434be5872808d7c70c8a0ee2c95c1eceac659a2bfeeba53c67b9f423551e1c38a34981981885a0579483a056d932aefaabd796733323e1ca7f3609c215b948d69402c9f03d04f75d22ce83181c20c53eb4fdd512e384bb928a8ef20cfabc58c0267cceb99ddcd8855ba89429821c2e5b83e2d0185dfb0d265bd2fc915fdf9363ffd4e0d65bb4df6ddf214d6f1be45343c8db8702db56f4fe9025e3dd8103d4265570162fc0f62959cd71801d845b189eb3c48c5af0d2d42d0afa5eb2acbd19ab4b83f2337af9eefe3fbe8619fb425b056ce42845b98797af3f5ba53cfaf238f95aee4d529ba040ba5ae1f34f1c6a70203010001
      CryptographicAlgorithm (Enumeration/4): RSA
      CryptographicLength (Integer/4): 2048

❯ ppkmip -f sample.xml -o prettyhex
420079 | 01 | 000001c8
  420057 | 05 | 00000004 | 0000000300000000
  420091 | 01 | 00000038
    420008 | 01 | 00000030
      42000a | 07 | 00000018 | 43727970746f67726170686963205573616765204d61736b
      42000b | 02 | 00000004 | 0000003000000000
  42006d | 01 | 00000170
    420040 | 01 | 00000168
      420042 | 05 | 00000004 | 0000000300000000
      420045 | 01 | 00000130
        420043 | 08 | 00000126 | 30820122300d06092a864886f70d01010105000382010f003082010a0282010100a6aba5b452b2d8f5565862c2a6237609803434be5872808d7c70c8a0ee2c95c1eceac659a2bfeeba53c67b9f423551e1c38a34981981885a0579483a056d932aefaabd796733323e1ca7f3609c215b948d69402c9f03d04f75d22ce83181c20c53eb4fdd512e384bb928a8ef20cfabc58c0267cceb99ddcd8855ba89429821c2e5b83e2d0185dfb0d265bd2fc915fdf9363ffd4e0d65bb4df6ddf214d6f1be45343c8db8702db56f4fe9025e3dd8103d4265570162fc0f62959cd71801d845b189eb3c48c5af0d2d42d0afa5eb2acbd19ab4b83f2337af9eefe3fbe8619fb425b056ce42845b98797af3f5ba53cfaf238f95aee4d529ba040ba5ae1f34f1c6a702030100010000
      420028 | 05 | 00000004 | 0000000400000000
      42002a | 02 | 00000004 | 0000080000000000⏎    
```

**Comment by pkumarex** [comment]
Thanks for the reply.

Adding the code for request message ,

data, err := hex.DecodeString("30819e300d06092a864886f70d010101050003818c003081880281805525ecd049f6fc292ebe3d8488f20cc3d994187f5285e6917828ecc1edb6080eddb1bc02b5524728d112b4214c6b4541913975acb6a5238a7af848ef965e5beb333ed5d8b7d9fd21bed4bba8c597269ce258c95618b2d2a679bdca6de8eb4d9baff226e11e59f6538593b243bcb71e48fb75df999865ba9c3c7b2a4d2b1dadcf0203010001")

	msg := kmip.RequestMessage{
		RequestHeader: kmip.RequestHeader{
			ProtocolVersion: kmip.ProtocolVersion{
				ProtocolVersionMajor: 1,
				ProtocolVersionMinor: 4,
			},
			BatchCount: 1,
			//Authentication: auth,
		},
		BatchItem: []kmip.RequestBatchItem{
			{
				Operation: kmip14.OperationRegister,
				RequestPayload: kmip.RegisterRequestPayload{
					ObjectType: kmip14.ObjectTypePublicKey,
					TemplateAttribute: kmip.TemplateAttribute{
						Attribute: []kmip.Attribute{
							{
								AttributeName:  "Cryptographic Usage Mask",
								AttributeValue: kmip14.CryptographicUsageMaskWrapKey | kmip14.CryptographicUsageMaskUnwrapKey,
							},
						},
					},
					PublicKey: &kmip.PublicKey{
						KeyBlock: kmip.KeyBlock{
							KeyFormatType:          kmip14.KeyFormatTypeRaw,
							CryptographicAlgorithm: kmip14.CryptographicAlgorithmRSA,
							CryptographicLength:    2048,
							KeyValue: kmip.KeyValue{
								KeyMaterial: data,
							},
						},
					},
				},
			},
		},
	}

This seems to work in pykmip. 
In thales, it shows the error : 
ResultMessage (TextString/174): Server error [417/NCERRInvalidOrMissingKeyData: Could not decode key from key material]: Number of bits in key material (1023) is incorrect, expected 2048 bits. HTTP code:422

**Comment by pkumarex** [comment]
Hi,

Key material was not correct. It seems that pykmip does not actually validate the key material. 
I am not sure why in the other workspace i am getting different key material in request message, need to dig further for that.
I am able to register in thales with correct key material using kmip-go.

Thank you.
