### ISSUE TITLE
Invalid Tag error in TTLV marshal

### ISSUE THREAD

**Issue by pkumarex** [ThalesGroup/kmip-go#12]
Getting invalid tag error when MaskHashingAlgorithm is provided in cryptographicParamters in request message.
Same error is seen in response also in get wrapped key when this value is provided in request message.

Sample Request Message :

CommonTemplateAttribute: kmip.TemplateAttribute{
						Attribute: []kmip.Attribute{
							{
								AttributeName:  "Cryptographic Algorithm",
								AttributeValue: kmip14.CryptographicAlgorithmRSA,
							},
							{
								AttributeName:  "Cryptographic Length",
								AttributeValue: int32(4096),
							},
							{
								AttributeName:  "Cryptographic Parameters",
								AttributeValue: cryptographicParameters,
							},
						}

Where cryptographicParamters is : 

	cryptographicParameters := kmip.CryptographicParameters{
		PaddingMethod:        kmip14.PaddingMethodOAEP,
		HashingAlgorithm:     kmip14.HashingAlgorithmSHA_384,
		MaskHashingAlgorithm: kmip14.HashingAlgorithmSHA_384,
	}

Kindly let us know, how to marshal the request message.

Thanks.

**Comment by pkumarex** [comment]
Based on Analysis, found that the error in marshalling is  due to invalid field name for MaskHashingAlgorithm, it should be MaskGeneratorHashingAlgorithm. Can you please add a commit for that ?

Thanks.

**Comment by ansel1** [comment]
nice catch.  pushed the fix to master.
