### ISSUE TITLE
tag a new release with the latest changes

### ISSUE THREAD

**Issue by yogev-lb** [ThalesGroup/kmip-go#14]
The latest tag is 0.0.5 which is a year older then the latest master code.

When one `go get ...` the pkg he will get:

```go
github.com/gemalto/kmip-go v0.0.5
```

which does not include all the code in master.

It is very confusing to see the `object_base_test.go` examples and try to run them against the `go get...` package and see it is not compiling...

**Comment by ansel1** [comment]
Done
