### ISSUE TITLE
Release status/milestone check

### ISSUE THREAD

**Issue by humblec** [ThalesGroup/kmip-go#20]
With this report, we would like to check the release cadence of this repo if available.  We are mainly looking for 0.0.8 with the changes merged a month ago https://github.com/ThalesGroup/kmip-go/pull/19.

Is there any release planned in this month or soon? 

Cc @baum

**Comment by humblec** [comment]
Cc @ansel1 @jskazinski

**Comment by jskazinski** [comment]
I have additional changes and I will merge/rebase and update the PR in the next week.

**Comment by ansel1** [comment]
I don't mind bumping the version twice if you need a release now.  Or I can wait for @jskazinski PR updates.  Let me know what you prefer.

**Comment by humblec** [comment]
@ansel1 if its not of concern, appreciated if we can have a release . If there are more changes required the future releases can be scheduled accordingly.

**Comment by humblec** [comment]
@ansel1 shall we have a release soon?

**Comment by ansel1** [comment]
Sorry, yes.  This is in my inbox every morning staring at me :).  I've just been slammed at work.

**Comment by humblec** [comment]
> Sorry, yes. This is in my inbox every morning staring at me :). I've just been slammed at work.

nw :)... I would have requested "a release at the earliest" instead of 'soon' :)

**Comment by ansel1** [comment]
Finally released...
