### ISSUE TITLE
Issues faced with Kmip Go client implementation

### ISSUE THREAD

**Issue by pdharshini** [ThalesGroup/kmip-go#4]
Hi,

We are trying to use the Kmip Go client implementation, connect to a Thales CipherTrust manager and perform key operations. But we are running into following issues
1. DiscoverVersions example provided is not working properly. We had to make some modifications (in example_test.go) to make it work.
2. We see that Kmip 2.0 related definitions are available. Can you let us know if this has been verified against a Kmip 2.0 compliant server?
3. For get and destrou key operations, we dont see structures available
4. Do we have encoding support for Map types? When creating the request for Create key, we are not able to encode the Map type attributes.

Could you please provide an update on the above items?

**Comment by ansel1** [comment]
1. It looks like the issue was that pykmip-server doesn't support 1.4.  It only goes up to 1.2, and doesn't support the ClientCorrelationValue.  I've add a pykmip server services to the project's docker compose stack, and added a test for DiscoverVersions which works against that server.  Run `make` to test it, and see the code in base_objects_test.go
2. No, it hasn't been verified against a real server.
3. The root package does not have a complete set of structures mirroring all the structures defined in the spec.  The ttlv package was really the focus of this project.  The ttlv package should be functionally complete, and has unit tests covering it all.  The root package was intended to grow into a full server and client implementation, but was not completed.  But defining additional structures needed for your use case is pretty simple.  You create a golang struct matching the KMIP structure, and use the ttlv package's marshal/unmarshal functions to translate the structure to and from TTLV.
4. I'm not clear on the context.  TTLV doesn't have a data structure that works like a map, so it's unclear how to convert between TTLV values and maps.  Do you have some sample code for what you are trying to do?

**Comment by pdharshini** [comment]
Thanks for your response. 
1. We have deployed a PyKmip server that supports upto kmip 2.0. With that server, we could run the discoverVersions command successfully. But we had remove the ClientCorrelationValue and only then it started working.
2. Regarding the encoding support for Map - we are trying to implement create key operation. For that we had to use templates attribute struct - https://github.com/ThalesGroup/kmip-go/blob/master/base_objects.go#L392
We are not able to encode the Map type attributes when creating the request payload for create key operation.

**Comment by ansel1** [comment]
1. yeah, I look at pykmip's code.  It doesn't support the ClientCorrelationValue, and it can't handle unexpected values in the request header.  It's also sensitive to the order of the values.
2. I tested marshaling and unmarshaling TemplateAttribute.  It worked fine, so long as I added attributes with the methods, rather than trying to modifying the map directly.  That said, I think the implementation was overly complicated.  I was trying to ensure index numbers were incremented correctly when you add attributes.  But on a closer read of the spec, client's don't need to worry about setting index numbers when creating objects or adding attributes to existing objects.  It's the server's responsibility to assign indexes.  The client can just leave them all 0.  So I reimplemented TemplateAttribute more simply, using an array of Attribute structs.  Let me know if you still encounter an issue. See base_objects_test.go:TestTemplateAttribute_marshal() for examples.

**Comment by pkumarex** [comment]
Thank you for your response. We will try out the simplied templated attributes for create key.

I have two more queries :

1) We tried out the get key operation. We were able to get the response successfully for symmetric key.
But for private key, we are getting the following error : 
%!v(PANIC=String method: ResponseMessage: BatchItem: ResponsePayload: PrivateKey: KeyBlock: invalid tag)
Is there anything we need to change for decoding the response message ?

2) Template Attributes is in accordance with kmip 1.4 specification, if we want to connect with pykmip 2.0, create key structure does not support template attributes, will the structure change for that work for pykmip 2.0 also ?

**Comment by ansel1** [comment]
Those structures are designed for 1.4, so I can believe they may not work with a 2.0 server.

I would recommend creating your own structs.  The `ttlv` package can marshal TTLV to golang structs, in much the same way that the `json` package marshals JSON to golang structs.  The docs in the `ttlv` describe how the mapping works.  So it is quite simple to define your own structs to marshal TTLV in and out of.  The marshaler uses a combination of naming conventions, type conversion conventions, and struct tags to map TTLV to struct fields.

**Comment by pkumarex** [comment]
Hi ,

We have few more queries :

1) In key wrapping supported ? If so, would it be possible to provide an example ?

2) We tried get operation with kmip 1.4 and kmip 2.0 servers. We changed the protocol version alone based on server version and request payload is same. It works as long as only kmip14 package is imported. If kmip20 package is imported it is not working.
We observer the following,
If only kmip14 package is imported, the encoded request message looks like this ,
    RequestPayload (Structure/16):
      UniqueIdentifier (TextString/2): 24

If kmip20 package is imported along with kmip14 or only kmip20 package is imported , it looks like below,
RequestPayload (Structure/16):
      UniqueIdentifier (Enumeration/4): 0x00000018

In this second case only, get operation is not working.

The same issue is observed with destroy key also.

3) We created structs for create symmetric key and create key pair for Kmip 2.0.
Kindly take a look at the below structs and let us know if this is fine.

// Create Key 
type CreateRequestPayload struct {
	ObjectType kmip20.ObjectType
	Attributes Attributes
}

type Attributes struct {
	CryptographicAlgorithm ttlv.EnumValue
	CryptographicLength    int32
	CryptographicUsageMask int32
}

type CreateResponsePayload struct {
	UniqueIdentifier string
}

// Create key pair request payload - kmip 2.0
type CreateKeyPairRequestPayload struct {
	CommonAttributes     CommonAttributes
	PrivateKeyAttributes PrivateKeyAttributes
	PublicKeyAttributes  PublicKeyAttributes
}

type CommonAttributes struct {
	CryptographicAlgorithm ttlv.EnumValue
	CryptographicLength    int32
}

type PrivateKeyAttributes struct {
	CryptographicUsageMask int32
}

type PublicKeyAttributes struct {
	CryptographicUsageMask int32
}

Thank you.

**Comment by ansel1** [comment]
1. kmip-go doesn't implement any crypto.  It would be up to you to implement the key wrapping.  Ultimately, you're wrapping process should return a []byte, which you would place in the SymmetricKey.KeyBlock.KeyValue attribute, as a []byte (KeyValue can take either  []byte value, for wrapped keys, or a KeyValue Structure for unwrapped keys).
2. Can you show me what structure you marshaled that resulted in those values?  kmip20 complicates UniqueIdentifiers.  In kmip14, UniqueIdentifiers are always strings.  But in 2.0, the value of the UniqueIdentifier tag can be encoded as either a string, a Unique Identifier Enumeration, or an int.  The spec is very vague about how to interpret the enum and int values, but they seem to be ways to refer to different Placeholder IDs in batched requests.  The enum values refer to the Placeholder UniqueIdentifier set by the last batch item with a matching operation, and int refers to the Placeholder UniqueIdentifier set by the batch item with that index.
3. That looks like it would work, but there are a couple attributes which could be more strongly typed.

I pushed some updates with examples of how I would represent  CreateRequest/ResponsePayload and CreateKeyPairRequest/ResponsePayload, along with some tests to demonstration.  See kmip20/payloads.go and payloads_test.go.  I also demonstrated a custom struct for the UniqueIdentifier union, in kmip20/unique_identifier.go.  

While implementing, I noticed that my kmip20.json was missing a couple tags.  It looks like they were last minute additions to the spec that were added after I created that .json manifest.  I added them and regenerated the go code.  It was the Common Protection Storage Masks, Private Protection Storage Masks, and Public Protection Storage Masks.

**Comment by pkumarex** [comment]
Able to perform get operation when kmip 20 package is imported with new changes. Many thanks !

Regarding the key wrapping, what I meant to ask was to perform get operation with key wrapping.
Implemented the following struct :
// GetRequest is a Get Request Payload
type GetRequestPayload struct {
	UniqueIdentifier         kmip20.UniqueIdentifierValue
	KeyWrappingSpecification KeyWrappingSpecification
}

type KeyWrappingSpecification struct {
	WrappingMethod           kmip14.WrappingMethod `ttlv:",omitempty"`
	EncryptionKeyInformation EncryptionKeyInformation
	EncodingOption           kmip14.EncodingOption `ttlv:",omitempty" default:"TTLVEncoding"`
}

type EncryptionKeyInformation struct {
	UniqueIdentifier kmip20.UniqueIdentifierValue
}

Prior to this, created a symmetric key with cryptographic usage mask as wrap key.
Activated the key.

But while marshalling this struct, EncodingOption seems to be not marshalled properly.
KeyWrappingSpecification (Structure/56):
        WrappingMethod (Enumeration/4): Encrypt
        EncryptionKeyInformation (Structure/16):
          UniqueIdentifier (TextString/3): 638
        **EncodingOption (Enumeration/4): TTLVEncoding**

In response, the following is received ,
ResultStatus (Enumeration/4): OperationFailed
    ResultReason (Enumeration/4): EncodingOptionError
    ResultMessage (TextString/64): Encoding option 'EncodingOption.TTLV_ENCODING' is not supported.

Do I need to specify encoding option in a different way ?

**Comment by ansel1** [comment]
pykmip just doesn't support TTLVEncoding.  It only supports the "NoEncoding" option.  Try setting EncodingOption to kmip14.EncodingOptionNoEncoding.

Btw, kmip-go doesn't support the "default" attribute tag.  That will just be ignored.

**Comment by mshamn6x** [comment]
@ansel1 Tried creating EC keys using thales kmip-go, formed request message as following,  but received  "Invalid Attribute [Recommended Curve]", I created request with "RecommendedCurve" (without space) then also received the same error.

```
---------- Request of create key pair - EC Key --------
RequestMessage (Structure/344):
  RequestHeader (Structure/56):
    ProtocolVersion (Structure/32):
      ProtocolVersionMajor (Integer/4): 1
      ProtocolVersionMinor (Integer/4): 4
    BatchCount (Integer/4): 1
  BatchItem (Structure/272):
    Operation (Enumeration/4): CreateKeyPair
    RequestPayload (Structure/248):
      CommonTemplateAttribute (Structure/112):
        Attribute (Structure/48):
          AttributeName (TextString/23): Cryptographic Algorithm
          AttributeValue (Enumeration/4): 0x0000001a
        Attribute (Structure/48):
          AttributeName (TextString/17): Recommended Curve
          AttributeValue (Enumeration/4): 0x0000000a
      PrivateKeyTemplateAttribute (Structure/56):
        Attribute (Structure/48):
          AttributeName (TextString/24): Cryptographic Usage Mask
          AttributeValue (Integer/4): 8
      PublicKeyTemplateAttribute (Structure/56):
        Attribute (Structure/48):
          AttributeName (TextString/24): Cryptographic Usage Mask
          AttributeValue (Integer/4): 4
---------- Response of create key pair - EC Key --------
ResponseMessage (Structure/152):
  ResponseHeader (Structure/56):
    ProtocolVersion (Structure/32):
      ProtocolVersionMajor (Integer/4): 1
      ProtocolVersionMinor (Integer/4): 4
    TimeStamp (DateTime/8): 2021-05-11 09:31:39 +0000 UTC
  BatchItem (Structure/80):
    ResultStatus (Enumeration/4): OperationFailed
    ResultReason (Enumeration/4): InvalidMessage
    ResultMessage (TextString/37): Invalid Attribute [Recommended Curve]

```

Tried request message with "Cryptographic Length", then also retrieved  "InvalidField" , Incorrect curve id or size error message in response. 

```
---------- Request of create key pair - EC Key --------
RequestMessage (Structure/344):
  RequestHeader (Structure/56):
    ProtocolVersion (Structure/32):
      ProtocolVersionMajor (Integer/4): 1
      ProtocolVersionMinor (Integer/4): 4
    BatchCount (Integer/4): 1
  BatchItem (Structure/272):
    Operation (Enumeration/4): CreateKeyPair
    RequestPayload (Structure/248):
      CommonTemplateAttribute (Structure/112):
        Attribute (Structure/48):
          AttributeName (TextString/23): Cryptographic Algorithm
          AttributeValue (Enumeration/4): 0x0000001a
        Attribute (Structure/48):
          AttributeName (TextString/20): Cryptographic Length
          AttributeValue (Integer/4): 224
      PrivateKeyTemplateAttribute (Structure/56):
        Attribute (Structure/48):
          AttributeName (TextString/24): Cryptographic Usage Mask
          AttributeValue (Integer/4): 8
      PublicKeyTemplateAttribute (Structure/56):
        Attribute (Structure/48):
          AttributeName (TextString/24): Cryptographic Usage Mask
          AttributeValue (Integer/4): 4
---------- Response of create key pair - EC Key --------
ResponseMessage (Structure/176):
  ResponseHeader (Structure/72):
    ProtocolVersion (Structure/32):
      ProtocolVersionMajor (Integer/4): 1
      ProtocolVersionMinor (Integer/4): 4
    TimeStamp (DateTime/8): 2021-05-11 12:22:23 +0000 UTC
    BatchCount (Integer/4): 1
  BatchItem (Structure/88):
    Operation (Enumeration/4): CreateKeyPair
    ResultStatus (Enumeration/4): OperationFailed
    ResultReason (Enumeration/4): InvalidField
    ResultMessage (TextString/26): Incorrect curve id or size

```
If possible can you add sample request message to perform, EC key-pair create operation?

**Comment by ansel1** [comment]
Have you checked the spec's test cases doc for examples?  http://docs.oasis-open.org/kmip/testcases/v1.4/cn01/kmip-testcases-v1.4-cn01.html#_Toc479076963

**Comment by mshamn6x** [comment]
@ansel1 Yes, request message construction based on this example only, and able to create SECP256k1 key, Here QLength is optional field right as mentioned in spec.

I need to create EC key-pair length with algorithm SECP256R1, SECP384R1, SECP521R1 and PRIMEV1. So I tried creating EC key pair with recommended curve type P256, P384, P521 and P256 respectively. 

These above mentioned curvetypes are available in UI and create EC key pair operation is succeeded ,

![image](https://user-images.githubusercontent.com/66402782/118983212-d0413000-b999-11eb-8aca-8b33fe27c6d9.png)


But when trying to create this from KMIP getting following error "Incorrect curve id or size". Note: For all above mentioned RecommendedCurve faced the same error.

```
---------- Request of create key pair - EC Key P_256--------
RequestMessage (Structure/360):
  RequestHeader (Structure/56):
    ProtocolVersion (Structure/32):
      ProtocolVersionMajor (Integer/4): 1
      ProtocolVersionMinor (Integer/4): 4
    BatchCount (Integer/4): 1
  BatchItem (Structure/288):
    Operation (Enumeration/4): CreateKeyPair
    RequestPayload (Structure/264):
      CommonTemplateAttribute (Structure/128):
        Attribute (Structure/48):
          AttributeName (TextString/23): Cryptographic Algorithm
          AttributeValue (Enumeration/4): 0x0000001a
        Attribute (Structure/64):
          AttributeName (TextString/31): Cryptographic Domain Parameters
          AttributeValue (Structure/16):
            RecommendedCurve (Enumeration/4): P_256
      PrivateKeyTemplateAttribute (Structure/56):
        Attribute (Structure/48):
          AttributeName (TextString/24): Cryptographic Usage Mask
          AttributeValue (Integer/4): 8
      PublicKeyTemplateAttribute (Structure/56):
        Attribute (Structure/48):
          AttributeName (TextString/24): Cryptographic Usage Mask
          AttributeValue (Integer/4): 4
---------- Response of create key pair - EC Key --------
ResponseMessage (Structure/176):
  ResponseHeader (Structure/72):
    ProtocolVersion (Structure/32):
      ProtocolVersionMajor (Integer/4): 1
      ProtocolVersionMinor (Integer/4): 4
    TimeStamp (DateTime/8): 2021-05-20 12:49:12 +0000 UTC
    BatchCount (Integer/4): 1
  BatchItem (Structure/88):
    Operation (Enumeration/4): CreateKeyPair
    ResultStatus (Enumeration/4): OperationFailed
    ResultReason (Enumeration/4): InvalidField
    ResultMessage (TextString/26): Incorrect curve id or size
```

Refer following used request message, 

```

msg := kmip.RequestMessage{
		RequestHeader: kmip.RequestHeader{
			ProtocolVersion: kmip.ProtocolVersion{
				ProtocolVersionMajor: 1,
				ProtocolVersionMinor: 4,
			},
			BatchCount: 1,
		},
		BatchItem: []kmip.RequestBatchItem{
			{
				Operation: 2,
				RequestPayload: kmip.CreateKeyPairRequestPayload{
					CommonTemplateAttribute: &kmip.TemplateAttribute{
						Attribute: []kmip.Attribute{
							{
								AttributeName:  "Cryptographic Algorithm",
								AttributeValue: kmip14.CryptographicAlgorithmEC,
							},
							{
								AttributeName: "Cryptographic Domain Parameters",
								AttributeValue: CryptographicDomainParameters{
									RecommendedCurve: kmip14.RecommendedCurveP_521,
								},
							},
						},
					},
					PrivateKeyTemplateAttribute: &kmip.TemplateAttribute{
						Attribute: []kmip.Attribute{
							{
								AttributeName:  "Cryptographic Usage Mask",
								AttributeValue: kmip14.CryptographicUsageMaskDecrypt,
							},
						},
					},
					PublicKeyTemplateAttribute: &kmip.TemplateAttribute{
						Attribute: []kmip.Attribute{
							{
								AttributeName:  "Cryptographic Usage Mask",
								AttributeValue: kmip14.CryptographicUsageMaskEncrypt,
							},
						},
					},
				},
			},
		},
	}
```
