### ISSUE TITLE
tls connection has parameter insecureSkipVerify as true in test file

### ISSUE THREAD

**Issue by pkumarex** [ThalesGroup/kmip-go#9]
In the pykmip server examples, insecureSkipverify is set as true. Is it possible to use insecureSkipVerify as false and connect to pykmip or thales server ? 

For establishing tls connection to thales server, can connection be established with insecureSkipVerify as false ?

**Comment by ansel1** [comment]
We're just using go's built in tls support.  You can turn InsecureSkipVerify off, but then the KMIP server you connect to must have a cert issued by a valid CA in your system's trust store.  Or you can use go's tls APIs to configure your own trusted CAs.  

In other words, there is nothing unique about how this package, or KMIP, does tls.  It all works the same as described in go's docs about tls.
